CodeHelper::IOArchitect
Dependency<TDevice> CodeHelper::IOArchitect< TMessageToRead, TMessageToSend, TDevice >::Device
ReaderArchitect<TMessageToRead, TDevice> CodeHelper::IOArchitect< TMessageToRead, TMessageToSend, TDevice >::ReaderFlow
WriterArchitect<TMessageToSend, TDevice> CodeHelper::IOArchitect< TMessageToRead, TMessageToSend, TDevice >::WriterFlow
std::chrono::milliseconds CodeHelper::IOArchitect< TMessageToRead, TMessageToSend, TDevice >::MinObserverInterval
TaskDone CodeHelper::IOArchitect< TMessageToRead, TMessageToSend, TDevice >::DoneStatus
constexpr char CodeHelper::IOArchitect< TMessageToRead, TMessageToSend, TDevice >::Name[][]
Configurations CodeHelper::IOArchitect< TMessageToRead, TMessageToSend, TDevice >::Configure() noexcept
bool CodeHelper::IOArchitect< TMessageToRead, TMessageToSend, TDevice >::Check() noexcept override
用于检查任务的依赖状态，判断是否满足依赖，可以执行
如果任务可以执行，返回 true ，否则返回 false
Referenced by CodeHelper::DeviceIOTrigger< TMessageToRead, TMessageToSend, TDevice >::SetItem.
void CodeHelper::IOArchitect< TMessageToRead, TMessageToSend, TDevice >::Execute() noexcept override
执行任务
Referenced by CodeHelper::DeviceIOTrigger< TMessageToRead, TMessageToSend, TDevice >::SetItem.
std::ostream& CodeHelper::IOArchitect< TMessageToRead, TMessageToSend, TDevice >::GetName(std::ostream &stream) const noexcept override
std::ostream& CodeHelper::IOArchitect< TMessageToRead, TMessageToSend, TDevice >::GetBrief(std::ostream &stream) const noexcept override
bool CodeHelper::IOArchitect< TMessageToRead, TMessageToSend, TDevice >::IsDone() const noexcept override
用于判断任务是否已经执行完毕，要求判断的过程不对任务产生任何影响
只要任务执行完毕，即使是异常退出，都会返回 true ，其他情况会是 false
void CodeHelper::IOArchitect< TMessageToRead, TMessageToSend, TDevice >::Interrupt() noexcept override
要求中断任务，执行后可通过 IsDone 函数判断任务是否已经中断 任务一般通过在循环中检查此函数控制的一个标志量来提前中断任务，所以此函数不能保证立即中断任务
void CodeHelper::IOArchitect< TMessageToRead, TMessageToSend, TDevice >::Reset() noexcept override
要求重置任务状态，执行后可用过 IsDone 函数判断任务是否重置
Referenced by CodeHelper::DeviceIOTrigger< TMessageToRead, TMessageToSend, TDevice >::SetItem.